# Generated by Django 5.2.16 on 2026-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('expired', 'Expired'), ('near_expiry', 'Near expiry'), ('low_stock', 'Low stock'), ('hazard', 'Hazard')], max_length=20),
        ),
    ]
