# Generated by Django 5.2.16 on 2026-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_class_a', models.CharField(choices=[('none', 'None'), ('flammable', 'Flammable'), ('corrosive', 'Corrosive'), ('toxic', 'Toxic'), ('oxidizer', 'Oxidizer'), ('reactive', 'Reactive'), ('health', 'Health hazard'), ('environmental', 'Environmental hazard')], max_length=20)),
                ('hazard_class_b', models.CharField(choices=[('none', 'None'), ('flammable', 'Flammable'), ('corrosive', 'Corrosive'), ('toxic', 'Toxic'), ('oxidizer', 'Oxidizer'), ('reactive', 'Reactive'), ('health', 'Health hazard'), ('environmental', 'Environmental hazard')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], default='high', max_length=10)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hazard_class_a', 'hazard_class_b'), name='unique_hazard_pair')],
            },
        ),
    ]
