# Generated by Django 5.2.16 on 2026-07-23 08:08
# Hand-edited: Postgres can't cast bigint -> uuid in place, so this drops and
# recreates the id column instead of altering it. Safe because the table has
# zero rows at this point in the project (no data loss).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incompatibilityrule',
            name='id',
        ),
        migrations.AddField(
            model_name='incompatibilityrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
