# Generated by Django 5.2.16 on 2026-07-23 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0002_alter_incompatibilityrule_id'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incompatibilityrule',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Plain-language summary of what this rule detects.', max_length=255),
        ),
        migrations.AddField(
            model_name='incompatibilityrule',
            name='principle',
            field=models.CharField(blank=True, default='', help_text="Short named principle, e.g. 'Oxidizer–flammable segregation'.", max_length=100),
        ),
        migrations.AddField(
            model_name='incompatibilityrule',
            name='recommended_action',
            field=models.TextField(blank=True, default='', help_text='Concrete corrective action for laboratory personnel.'),
        ),
        migrations.AddField(
            model_name='incompatibilityrule',
            name='reference_source',
            field=models.CharField(blank=True, default='', help_text='General guidance this rule is drawn from (e.g. OSHA/NFPA/NOAA/Flinn).', max_length=255),
        ),
        migrations.AddField(
            model_name='incompatibilityrule',
            name='severity_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numeric counterpart to severity (critical=3, high=2, medium=1).'),
        ),
        migrations.AlterField(
            model_name='incompatibilityrule',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='The safety mechanism: why this pairing is dangerous.'),
        ),
        migrations.CreateModel(
            name='IncompatibilityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chemical_a_name', models.CharField(max_length=255)),
                ('chemical_a_hazard_class', models.CharField(choices=[('none', 'None'), ('flammable', 'Flammable'), ('corrosive', 'Corrosive'), ('toxic', 'Toxic'), ('oxidizer', 'Oxidizer'), ('reactive', 'Reactive'), ('health', 'Health hazard'), ('environmental', 'Environmental hazard')], max_length=20)),
                ('chemical_b_name', models.CharField(max_length=255)),
                ('chemical_b_hazard_class', models.CharField(choices=[('none', 'None'), ('flammable', 'Flammable'), ('corrosive', 'Corrosive'), ('toxic', 'Toxic'), ('oxidizer', 'Oxidizer'), ('reactive', 'Reactive'), ('health', 'Health hazard'), ('environmental', 'Environmental hazard')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('principle', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=10)),
                ('severity_level', models.PositiveSmallIntegerField()),
                ('recommended_action', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('chemical_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incompatibility_alerts_as_a', to='inventory.chemical')),
                ('chemical_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incompatibility_alerts_as_b', to='inventory.chemical')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incompatibility_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='hazards.incompatibilityrule')),
            ],
            options={
                'ordering': ['-severity_level', '-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('chemical_a', 'chemical_b', 'rule'), name='unique_active_incompatibility')],
            },
        ),
    ]
