# Generated by Django 5.2.16 on 2026-07-23 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(default='g', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('hazard_class', models.CharField(choices=[('none', 'None'), ('flammable', 'Flammable'), ('corrosive', 'Corrosive'), ('toxic', 'Toxic'), ('oxidizer', 'Oxidizer'), ('reactive', 'Reactive'), ('health', 'Health hazard'), ('environmental', 'Environmental hazard')], default='none', max_length=20)),
                ('ghs_category', models.JSONField(blank=True, default=list)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('supplier', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('near_expiry', 'Near expiry'), ('low_stock', 'Low stock'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chemicals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='inventory_c_status_a7283e_idx'), models.Index(fields=['hazard_class'], name='inventory_c_hazard__3a86ed_idx'), models.Index(fields=['expiry_date'], name='inventory_c_expiry__6948b1_idx')],
            },
        ),
    ]
