# Generated by Django 5.2.16 on 2026-08-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_chemical_barcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chemical',
            new_name='inventory_c_barcode_fd93e2_idx',
            old_name='inventory_c_barcode_idx',
        ),
    ]
