# Generated by Django 5.2.16 on 2026-07-23 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('restored', 'Restored'), ('deleted', 'Deleted')], max_length=20)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='inventory.chemical')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chemical', '-created_at'], name='audit_chemi_chemica_5c7860_idx')],
            },
        ),
    ]
